### ISSUE TITLE
[suggestion] Define posts date with front mater instead of file name.

### ISSUE THREAD

**Issue by altavir** [JavaEden/Orchid#140]
Like 
```
---
title: My title
date: 04.11.2016
---
```

Also make date format adjustable in posts configuration since it is different for different countries. It could be done with simple string in `posts yml` like 
```
categories: ...
postPages: ...
dateFormat: "dd'.'MM'.'YYYY"
```

**Comment by altavir** [comment]
It seems, that it could be overridden with `publishDate`, but Orchid does not recognize the post if it does not follow date naming convention.

**Comment by cjbrooks12** [comment]
The post filename format is designed to match that of Jekyll, but allow them to be nested in directories for better organization. The format is always `year-month-day` so that the default filesystem ordering should also order them by date. 

Setting `publishDate` will override the date set in the filename, and are parsed as ISO-8601 timestamps, not locale-specific date formats (this all also matches Jekyll functionality). Overriding a post's `publishDate` will update its permalinks accordingly, and you are free to customize the permalink structure to whatever way works best for you.

```yaml
---
title: Post One
publishDate: '2018-06-13'
permalink: 'blog/:day/:month/:year/:slug'
---
# will render a page at /blog/13/6/2018/post-one
```
