### ISSUE TITLE
Empty collections for custom taxonomies

### ISSUE THREAD

**Issue by dmoyagoal** [JavaEden/Orchid#255]
I have a problem with taxonomies not being available from pages, I don't know whether it's a bug or just a function not supported. I've tried using the snippet for templates that you posted at Issue 50, but it wouldn't work:
( https://github.com/JavaEden/Orchid/issues/50 )

Unfortunately, the code you provided doesn't render anything, and the 'for' loop isn't executed, not even once. I have created the following taxonomies at `taxonomies.yml`, and the templates using them behave as if they are empty:

```yaml
taxonomies:
  - key: tags
    orderBy:
      - entryCount
  - key: productos
    orderBy:
      - title
    pageSize: 20
  - key: documentos
    orderBy:
      - title
    pageSize: 20
  - key: idioma
    orderBy:
      - title
    pageSize: 20
```

The admin page shows that these taxonomies are created, and they are visible at the "manage" dialog under Collections, but they have size 0. 
However, the Taxonomy base page shows all the pages that I have included through an archetype in the config.yml configuration shown below; they just aren't included as variables in the templates. These are the values I have assigned to my collections at config.yml:

```yaml
pages:
    Introduccion-GRm-EN:
        menu:
          - type: 'pageIds'
            structure: 'nested'
          - type: 'separator'
            title: 'GRmetro introduction'
          - type: 'pages'
            group: 'Introduccion-GRm-EN'
        parent: 'Introduccion GRm EN'
        productos:
            - 'GRMETRO'
        documentos:
            - 'Conceptos'
        idioma: 
            - 'EN'
    
    Manual-GB-ES-MU:
        template: 'Manual-GB-ES-MU'
        menu:
          - type: 'pageIds'
            structure: 'nested'
          - type: 'separator'
            title: 'GB MU'
          - type: 'pages'
            group: 'Manual-GB-ES-MU'
        parent: 'Manual GB ES MU'
        productos: 
            - 'GB'
        documentos:
            - 'Manuales'
        idioma: 
            - 'ES'
```

Besides, I have problems with the automatic treatment of names for pages and collections; the product names are variations of CamelCase, and they get mangled by being separated at wrong places (for example GRm is a product name composed of the particles "GR" and "m", but it becomes "G" and "Rm"). Is there some parameter to disable this conversion and have all names unchanged, like the 'UglyURLs' parameter in Hugo?

Thanks for your support!
