### ISSUE TITLE
Orchid Starter Guide isn't very beginner friendly.

### ISSUE THREAD

**Issue by Andre601** [JavaEden/Orchid#384]
I want to try out Orchid on my multi-module project, but it does nothing more than generating the default pages that you get when trying out the Java-example.

I already tried to create a `config.yml` in the main `src/main/resources` directory but it didn't work. Putting it directly into the root directory also didn't change anything.

I am aware that the gitter chat is your (prefered) way of giving support, but as of writing this issue is noone active there and my personal guess is, that I won't be online when I receive an answer, making support delayed and unpleasant.
If there is any other form of comunication, such as a Discord chat or similar would I really appreciate to get forwarded to it.

My main issue is - as described above - is that the config seems to get fully ignored.
I'm in the process of turning my single-module project into a multi-module one and therefore use the [multi module setup](https://orchid.run/plugins/orchidjavadoc#multi-module-usage) for the config.

But no matter if I put the config file in `src/main/resources`, just the root directory or in a dedicated docs module does Orchid do absolutely nothing with the projects module setup.

My config.yml currently looks like this:
```yaml
javadoc:
  modules:
  - name: 'JavaBotBlockAPI (Core)'
    slug: 'javabotblockapi-core'
    sourceDirs: ['../core/src/main/java']
  - name: 'JavaBotBlockAPI (JDA-Module)'
    slug: 'javabotblockapi-jda'
    sourceDirs: ['../jda-module/src/main/java']
    relatedModules: ['JavaBotBlockAPI (Core)', 'JavaBotBlockAPI (Request-Module)']
  - name: 'JavaBotBlockAPI (Request-Module)'
    slug: 'javabotblockapi-request'
    sourceDirs: ['../request-module/src/main/java']
```

I of course added the javadoc plugin as a orchidRuntime dependency to the source build.gradle.

I'm frustrated beyond any belief and close to just throwing this entire thing away.

**Comment by cjbrooks12** [comment]
I apologize for the delay on Gitter. I just moved and have not been online much in the past few weeks. 

There are a few things to check:

1) Orchid should be in a separate subproject from the other modules
2) `config.yml` should be in `src/orchid/resources` of its module (not `src/main/resources`)
3) The paths linked to in `sourceDirs` are relative to the `config.yml`. To check you have the right paths, you can `cd` into `src/orchid/resources` and `ls` your way through parent directories to get to the right source directories

**Comment by Andre601** [comment]
> 1. Orchid should be in a separate repo from the other modules
> 2. `config.yml` should be in `src/orchid/resources` of its module (not `src/main/resources`)
> 3. The paths linked to in `sourceDirs` are relative to the `config.yml`. To check you have the right paths, you can `cd` into `src/orchid/resources` and `ls` your way through parent directories to get to the right source directories

1. By "separate repo" you mean a separate module (like the docs module that was suggested in the kotlin setup guide)?
2. This is poorly explained in the guide as it (at most) mentions that it has to be in src/orchid/resources (Just found it a few seconds before your reply) but not if this directory has to be in its own module/directory, or if it has to be as a part of the root project itself.

**Comment by cjbrooks12** [comment]
Yes, I meant separate subproject, I've corrected the comment above. 

And [this tutorial](https://orchid.run/wiki/learn/tutorials/how-to-document-kotlin) was written to be read top-down slowly and carefully, as it is a literal step-by-step guide, not as a quick reference. The [Homepage subheader](https://orchid.run/wiki/learn/tutorials/how-to-document-kotlin#homepage) is the first time it mentions adding Orchid-specific files to the site, and I tried to be pretty clear about which directory these files need to be in:

> The first thing anyone will see when landing on your site is your Homepage. Orchid creates this page based on a `homepage.md` file in the root of your site's resources, which are located by default in `src/orchid/resources`.

Additionally, every code snippet in that tutorial includes the full path of that file in the project as the first line of the snippet, so they all include `src/orchid/resources`, not `src/main/resources`. I tried to be as clear as I could about the locations of all files for using Orchid, but if you have suggestions about how to make it more clear, I would appreciate the tips so I can get it corrected!

**Comment by Andre601** [comment]
Maybe adding a small section called `default/source locations` or something alike to the  [Your first orchid Site](https://orchid.run/wiki/learn/tutorials/your-first-orchid-site) may be an idea, to inform right from the beginning, that Orchid-related files are stored in a specific direction (and that you can alter it if so desired).

It's a small change, but sure wouldn't hurt.

About my issue: I got the Orchid plugin now to find the sources for Javadoc, but I now face the issue, where it can't find pages?
I essentially want Orchid to link to other modules, if I have a `{@link path}` tag in the comments pointing to a different modules.
If I understand it correctly do I have to set `relatedModules` as an option in the config, to enable this?
When I do this, do I set this setting on the modules that link TO the specified module, or in the module, that I will link to?
Also, when I define a slug, is that one used over the name in the relatedModules, or is just the name used?

Because I receive a lot of errors like these here:
```
[ERROR]     - Error creating anchor to [collectionType=javadoc, collectionId=JavaBotBlockAPI (Core), itemId=java.lang.Deprecated] from [http://localhost:8080/javadoc/javabotblockapi-core/org/botblock/javabotblockapi/core/annotations]: matching page not found
```

Edit: Looking over the errors does it seem to be a general issue with linking to external Java sources such as IOException
Is there a way to "tell" Orchid to use specific links to connect `{@link}` tags to external docs, similar to how the default Javadoc.exe can do this?

**Comment by cjbrooks12** [comment]
Orchid isn't able to link to stdlib classes or other sites' package-list files like normal Javadoc can, there's an open issue for this #237.

**Comment by Andre601** [comment]
Okay, thanks.
I assume there isn't any rough ETA on when this will become available?
Also, is there like any way to just "skip" those links for now?

**Comment by cjbrooks12** [comment]
No, I don't have an ETA on it yet, but it is one of the most requested features (along with #357).  Those links are already being skipped, it will just print out the text (not as a link) instead. The errors are only shown in [diagnose mode](https://orchid.run/wiki/user-manual/core-concepts/internal-links#debugging-internal-links), so the site should still be building successfully

**Comment by Andre601** [comment]
The site does build, but it still only gives the default pages without any changes made at all.

To give some context, the current project structure is build like this:
```
:root
  |
  |- core # Core module
  |    |- src
  |        |- main
  |            |- java
  |                |- org.botblock.javabotblockapi.core # From here on are Java classes and other folders with classes.
  |
  |- jda-module # JDA module
  |    |- src
  |        |- main
  |            |- java
  |                |- org.botblock.javabotblockapi.jda # From here on are Java classes and other folders with classes.
  |
  |- request-module # Request module
  |    |- src
  |        |- main
  |            |- java
  |                |- org.botblock.javabotblockapi.requests # From here on are Java classes and other folders with classes.
  |
  |- src
      |- orchid
          |- resources
              |- config.yml # See below
              |-  homepage.md # Is also not rendered at all
```

And the config.yml, as of now is like this:
```yaml
theme:
  primaryColor: '#2C2F33'

javadoc:
  modules:
  - name: 'JavaBotBlockAPI (Core)'
    slug: 'javabotblockapi-core'
    sourceDirs: ['../../../core/src/main/java']
  - name: 'JavaBotBlockAPI (JDA-Module)'
    slug: 'javabotblockapi-jda'
    sourceDirs: ['../../../jda-module/src/main/java']
    relatedModules: ['javabotblockapi-core', 'javabotblockapi-request']
  - name: 'JavaBotBlockAPI (Request-Module)'
    slug: 'javabotblockapi-request'
    sourceDirs: ['../../../request-module/src/main/java']
```
